Repository data-apis/dataframe-api, pull requests merged in 2023-01, with the labels that each got.

#96 API: isnull, isnan, reductions
  spec/API_specification/dataframe_api/dataframe_object.py
Labels: API design

#100 CI: deploy interchange protocol docs on each commit to main
  .github/workflows/protocol_docs.yml
Labels: CI, deployment

#98 Render API docstrings in `.py` files as html
  .gitignore
  spec/API_specification/column_object.rst
  spec/API_specification/column_selection.md
  spec/API_specification/dataframe_api/__init__.py
  spec/API_specification/dataframe_api/_types.py
  spec/API_specification/dataframe_api/dataframe_object.py
  spec/API_specification/dataframe_api/groupby_object.py
  spec/API_specification/dataframe_basics.md
  spec/API_specification/dataframe_object.rst
  spec/API_specification/filter_rows.md
  spec/API_specification/groupby_object.rst
  spec/API_specification/index.rst
  spec/_templates/attribute.rst
  spec/_templates/method.rst
  spec/_templates/property.rst
  spec/conf.py
Labels: documentation

#99 Update README with more context and links
  README.md
Labels: documentation
